export const BARROW_CORE_PINS = [
  {
    id: 1,
    n: "Home Base (196 Marsh St)",
    l: [54.11371, -3.218448],
    i: "🏠",
    set: "core",
    zone: "Residential",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 2,
    n: "Morrisons Retail",
    l: [54.108899, -3.224459],
    i: "🛒",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 3,
    n: "Salthouse Mills",
    l: [54.108788, -3.202556],
    i: "🏭",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 4,
    n: "The Cenotaph",
    l: [54.117756, -3.220668],
    i: "🕊️",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 5,
    n: "Park Bandstand",
    l: [54.116764, -3.21545],
    i: "🎤",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 6,
    n: "Park Railway",
    l: [54.117303, -3.213301],
    i: "🚂",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 7,
    n: "Boating Lake",
    l: [54.115711, -3.214812],
    i: "🚤",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 8,
    n: "Bridgegate Ave",
    l: [54.1298, -3.2015],
    i: "🛣️",
    set: "core",
    zone: "Outskirts",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 9,
    n: "Fryer's Lane",
    l: [54.1332, -3.1995],
    i: "🌿",
    set: "core",
    zone: "Outskirts",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 10,
    n: "Flashlight Bend",
    l: [54.135, -3.1985],
    i: "🔦",
    set: "core",
    zone: "Outskirts",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 11,
    n: "Red River Walk",
    l: [54.1365, -3.1978],
    i: "🌊",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 12,
    n: "Furness Abbey",
    l: [54.1375, -3.1965],
    i: "🏰",
    set: "core",
    zone: "Abbey/Ruins",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 13,
    n: "Dock Museum Anchor",
    l: [54.111672, -3.239817],
    i: "⚓",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 14,
    n: "Town Hall Clock",
    l: [54.11179, -3.227814],
    i: "🕰️",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 15,
    n: "The Custom House",
    l: [54.112861, -3.233361],
    i: "🏛️",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 16,
    n: "The Forum",
    l: [54.11178, -3.227541],
    i: "🎭",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 17,
    n: "Barrow Library",
    l: [54.114344, -3.231352],
    i: "📚",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 18,
    n: "Statue of Henry Schneider",
    l: [54.110993, -3.226199],
    i: "🗿",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 19,
    n: "Statue of James Ramsden",
    l: [54.114014, -3.230905],
    i: "🗿",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 20,
    n: "Old Fire Station",
    l: [54.11341, -3.23243],
    i: "🚒",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 21,
    n: "The Market Hall",
    l: [54.111512, -3.227291],
    i: "🍎",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 22,
    n: "The Duke of Edinburgh",
    l: [54.117008, -3.22582],
    i: "🍺",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 23,
    n: "Emlyn Hughes Statue",
    l: [54.117198, -3.225964],
    i: "⚽",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 24,
    n: "The Graving Dock",
    l: [54.112288, -3.240744],
    i: "⚓",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 25,
    n: "The Slag Bank",
    l: [54.129081, -3.240556],
    i: "⛰️",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 26,
    n: "Walney Bridge Entrance",
    l: [54.10781, -3.242316],
    i: "🌉",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 27,
    n: "Earnse Bay",
    l: [54.118717, -3.26881],
    i: "🌊",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 28,
    n: "Walney Lighthouse",
    l: [54.049374, -3.200183],
    i: "🗼",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 29,
    n: "The Round House",
    l: [54.097685, -3.258015],
    i: "🏠",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 30,
    n: "Biggar Village",
    l: [54.084516, -3.238156],
    i: "🏘️",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 31,
    n: "Piel Castle",
    l: [54.062467, -3.172938],
    i: "🏰",
    set: "core",
    zone: "Abbey/Ruins",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 32,
    n: "Roa Island Jetty",
    l: [54.07351, -3.174083],
    i: "⚓",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 33,
    n: "The Amphitheatre",
    l: [54.13435, -3.197034],
    i: "🎭",
    set: "core",
    zone: "Abbey/Ruins",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 34,
    n: "Abbey Ruins Marker",
    l: [54.134702, -3.196143],
    i: "🪨",
    set: "core",
    zone: "Abbey/Ruins",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 35,
    n: "Park Playground",
    l: [54.117774, -3.21632],
    i: "🛝",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 37,
    n: "Park Bowling Green",
    l: [54.117264, -3.216648],
    i: "⛳",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 38,
    n: "Park Café",
    l: [54.117355, -3.217025],
    i: "☕",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 39,
    n: "Ormsgill Reservoir",
    l: [54.126658, -3.231571],
    i: "💧",
    set: "core",
    zone: "Outskirts",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 40,
    n: "Barrow AFC Grounds",
    l: [54.123732, -3.233835],
    i: "⚽",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 41,
    n: "The Rugby Ground",
    l: [54.115278, -3.23406],
    i: "🏉",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 42,
    n: "Hollywood Park",
    l: [54.114964, -3.237282],
    i: "🎳",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 43,
    n: "Furness General Hospital",
    l: [54.133506, -3.20641],
    i: "🏥",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 44,
    n: "Rampside Needle",
    l: [54.086756, -3.161553],
    i: "🗼",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 45,
    n: "St. George’s Church",
    l: [54.108532, -3.220131],
    i: "⛪",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 46,
    n: "BAE Systems Main Gate",
    l: [54.107824, -3.229059],
    i: "🚢",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 47,
    n: "The Hindpool Tiger",
    l: [54.117171, -3.23643],
    i: "🐯",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 48,
    n: "Dalton Road Clock",
    l: [54.113436, -3.225185],
    i: "🕰️",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 49,
    n: "Voodoo Entrance",
    l: [54.1135, -3.226],
    i: "🎶",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 50,
    n: "The Bus Depot",
    l: [54.124984, -3.238193],
    i: "🚌",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 51,
    n: "North Walney Nature Reserve Gate",
    l: [54.121288, -3.270134],
    i: "🌊",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 52,
    n: "Sandy Gap Beach Access",
    l: [54.103753, -3.26122],
    i: "🏖️",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 53,
    n: "Walney Airfield Entrance",
    l: [54.121124, -3.257013],
    i: "✈️",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 54,
    n: "Vickerstown Park",
    l: [54.115351, -3.250952],
    i: "🌳",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 55,
    n: "The King Alfred Pub",
    l: [54.104361, -3.246295],
    i: "🍺",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 56,
    n: "Thorny Nook",
    l: [54.086341, -3.249388],
    i: "🌾",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 57,
    n: "South Walney Nature Reserve Entrance",
    l: [54.049029, -3.199424],
    i: "🦅",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 58,
    n: "Walney School",
    l: [54.105688, -3.258229],
    i: "🏫",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 59,
    n: "West Shore Park",
    l: [54.09715, -3.258958],
    i: "🌊",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 60,
    n: "Jubilee Bridge Mid-Point",
    l: [54.107675, -3.24387],
    i: "🌉",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 61,
    n: "Coast Road Entrance",
    l: [54.088312, -3.15976],
    i: "🛣️",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 62,
    n: "Lifeboat Station (Roa Island)",
    l: [54.07287, -3.173697],
    i: "🚤",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 63,
    n: "The Concle Inn",
    l: [54.083809, -3.172414],
    i: "🍺",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 64,
    n: "Furness Abbey Railway Ruins",
    l: [54.137605, -3.198454],
    i: "🚂",
    set: "core",
    zone: "Abbey/Ruins",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 65,
    n: "Amphitheatre Steps",
    l: [54.134723, -3.199773],
    i: "🪨",
    set: "core",
    zone: "Abbey/Ruins",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 66,
    n: "Abbey Road Baptist Church",
    l: [54.120787, -3.219426],
    i: "⛪",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 67,
    n: "The Nan Tait Centre",
    l: [54.1132, -3.2255],
    i: "🎨",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 68,
    n: "Barrow Fire Station",
    l: [54.124247, -3.23859],
    i: "🚒",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 69,
    n: "Submarine Memorial",
    l: [54.111452, -3.228052],
    i: "🚢",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 70,
    n: "The Victoria Hall",
    l: [54.116226, -3.224835],
    i: "🎭",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 71,
    n: "Barrow Golf Club",
    l: [54.140853, -3.219792],
    i: "⛳",
    set: "core",
    zone: "Outskirts",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 72,
    n: "Hawcoat Quarry",
    l: [54.133419, -3.226005],
    i: "🪨",
    set: "core",
    zone: "Outskirts",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 73,
    n: "St. Paul’s Church",
    l: [54.128161, -3.213691],
    i: "⛪",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 74,
    n: "The Strawberry Pub",
    l: [54.127641, -3.213498],
    i: "🍓",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 75,
    n: "Red River Waterfall",
    l: [54.118144, -3.19703],
    i: "💦",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 76,
    n: "Furness General Main Entrance",
    l: [54.136512, -3.210279],
    i: "🏥",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 77,
    n: "Roose Station Platform",
    l: [54.114828, -3.194084],
    i: "🚂",
    set: "core",
    zone: "Outskirts",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 78,
    n: "The Ship Inn (Piel Island)",
    l: [54.064098, -3.172772],
    i: "🍺",
    set: "core",
    zone: "Walney/Coastal",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 79,
    n: "Lifeboat Monument",
    l: [54.111624, -3.239883],
    i: "⚓",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 80,
    n: "Newby Terrace Play Area",
    l: [54.1185, -3.2335],
    i: "🛝",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 81,
    n: "BAE Systems (The Bridge)",
    l: [54.109233, -3.23946],
    i: "🚢",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 82,
    n: "Gas Terminals Main Gates",
    l: [54.098589, -3.173926],
    i: "🔥",
    set: "core",
    zone: "Industrial",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 83,
    n: "Kimberly-Clark Factory",
    l: [54.143936, -3.230962],
    i: "🏭",
    set: "core",
    zone: "Industrial",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 84,
    n: "Spiral Ramp (Town Center)",
    l: [54.125454, -3.23888],
    i: "🌀",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 85,
    n: "Barrow Park Greenhouse",
    l: [54.11803, -3.216973],
    i: "🌿",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 86,
    n: "Park Fitness Trail Start",
    l: [54.118062, -3.213948],
    i: "🏃",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 87,
    n: "Park Rockery",
    l: [54.118401, -3.218738],
    i: "🪨",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 88,
    n: "Park Rose Garden",
    l: [54.11779, -3.216026],
    i: "🌹",
    set: "core",
    zone: "Nature",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 89,
    n: "Greenway Path (Barrow Island)",
    l: [54.110553, -3.241691],
    i: "🌿",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 90,
    n: "Barrow Island Primary",
    l: [54.103947, -3.229953],
    i: "🏫",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 91,
    n: "Old Brickworks",
    l: [54.121427, -3.238341],
    i: "🧱",
    set: "core",
    zone: "Industrial",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 92,
    n: "Cavendish Dock Water Gate",
    l: [54.100186, -3.207629],
    i: "⚓",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 94,
    n: "Bowling Alley (Hollywood Park)",
    l: [54.114863, -3.237901],
    i: "🎳",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 95,
    n: "Skate Park",
    l: [54.121424, -3.243982],
    i: "🛹",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 96,
    n: "Dock Museum Submarine",
    l: [54.111995, -3.240591],
    i: "🚢",
    set: "core",
    zone: "Docks",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 97,
    n: "Barrow Cricket Club",
    l: [54.133856, -3.2069],
    i: "🏏",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 98,
    n: "12 Laws of the Universe Stone",
    l: [54.132256, -3.243878],
    i: "🔮",
    set: "core",
    zone: "Outskirts",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 99,
    n: "Spirit of Barrow Mural",
    l: [54.113448, -3.225193],
    i: "🎨",
    set: "core",
    zone: "Civic",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 100,
    n: "Final Boss Gate (Marsh St Entrance)",
    l: [54.113258, -3.218118],
    i: "🔥",
    set: "core",
    zone: "Residential",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 101,
    n: "wicks",
    l: [54.150245, -3.226811],
    i: "🔥",
    set: "core",
    zone: "Residential",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 102,
    n: "brew room",
    l: [54.149699, -3.227668],
    i: "🔥",
    set: "core",
    zone: "Residential",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 103,
    n: "reception",
    l: [54.15025, -3.226105],
    i: "🔥",
    set: "core",
    zone: "Residential",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 104,
    n: "bitches house",
    l: [54.117199, -3.232276],
    i: "🔥",
    set: "core",
    zone: "Residential",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 105,
    n: "dads house",
    l: [54.110114, -3.22239],
    i: "🔥",
    set: "core",
    zone: "Residential",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
  {
    id: 106,
    n: "tinas house",
    l: [54.116595, -3.234497],
    i: "🔥",
    set: "core",
    zone: "Residential",
    ar: { hint: "Scan around and confirm.", bearing: 0, tol: 180 },
  },
];

/* =========================
     ABBEY PINS
  ========================= */

export const ABBEY_PINS = [
  {
    id: "abbey_redriver_start",
    n: "Red River Walk Entrance",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "red_river",
    type: "start",
    l: [54.118164, -3.196948],
    i: "🌲",
  },
  {
    id: "abbey_redriver_bridge",
    n: "Red River Bridge",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "red_river",
    type: "story",
    l: [54.123073, -3.193007],
    i: "🌉",
  },
  {
    id: "abbey_redriver_bend",
    n: "Red River Woodland Bend",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "red_river",
    type: "quiz",
    l: [54.133017, -3.190272],
    i: "🌿",
  },
  {
    id: "abbey_valley_view",
    n: "Abbey Valley First View",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "red_river",
    type: "history",
    l: [54.134365, -3.196948],
    i: "👀",
  },
  {
    id: "abbey_amphitheatre_entry",
    n: "Amphitheatre Entrance",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "activity",
    l: [54.134455, -3.196085],
    i: "🏛️",
  },
  {
    id: "abbey_hospital_entry",
    n: "Hospital Path Entrance",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "hospital",
    type: "start",
    l: [54.14005, -3.200564],
    i: "🚶",
  },
  {
    id: "abbey_hospital_field",
    n: "Abbey Valley Approach",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "hospital",
    type: "quiz",
    l: [54.138578, -3.198646],
    i: "🌾",
  },
  {
    id: "abbey_amphitheatre_top",
    n: "Amphitheatre Top View",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "history",
    l: [54.133424, -3.196542],
    i: "🔭",
  },
  {
    id: "abbey_manor_gate",
    n: "Manor Hall Entrance",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "manor",
    type: "start",
    l: [54.133621, -3.203518],
    i: "🚪",
  },
  {
    id: "abbey_outer_field",
    n: "Abbey Outer Field",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "manor",
    type: "quiz",
    l: [54.134208, -3.196754],
    i: "🌱",
  },
  {
    id: "abbey_entry_path",
    n: "Abbey Entry Path",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "manor",
    type: "story",
    l: [54.135177, -3.199148],
    i: "🛤️",
  },
  {
    id: "abbey_woodland_entry",
    n: "Abbey Woodland Entrance",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "woodland",
    type: "start",
    l: [54.136219, -3.19656],
    i: "🌲",
  },
  {
    id: "abbey_monk_path",
    n: "Monks Woodland Path",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "woodland",
    type: "logic",
    l: [54.135568, -3.196588],
    i: "🕯️",
  },
  {
    id: "abbey_farmland",
    n: "Abbey Farmland View",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "woodland",
    type: "history",
    l: [54.134737, -3.193299],
    i: "🐑",
  },
  {
    id: "abbey_carpark",
    n: "Abbey Car Park",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "visitor",
    type: "start",
    l: [54.137006, -3.196757],
    i: "🚗",
  },
  {
    id: "abbey_ticket_gate",
    n: "Abbey Ticket Gate",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "visitor",
    type: "story",
    l: [54.13565, -3.199216],
    i: "🎟️",
  },
  {
    id: "abbey_cafe",
    n: "Abbey Café",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "visitor",
    type: "family",
    l: [54.134755, -3.196106],
    i: "☕",
  },
  {
    id: "abbey_visitor_area",
    n: "Visitor Centre Area",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: "visitor",
    type: "quiz",
    l: [54.137199, -3.198346],
    i: "ℹ️",
  },
  {
    id: "abbey_gate",
    n: "Abbey Entrance Gate",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "history",
    l: [54.137465, -3.198859],
    i: "⛩️",
  },
  {
    id: "abbey_church",
    n: "Abbey Church Ruins",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "quiz",
    l: [54.134967, -3.197482],
    i: "⛪",
  },
  {
    id: "abbey_cloister",
    n: "Cloister Walk",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "logic",
    l: [54.135561, -3.197684],
    i: "🚶‍♂️",
  },
  {
    id: "abbey_chapter_house",
    n: "Chapter House Area",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "history",
    l: [54.133966, -3.196801],
    i: "📜",
  },
  {
    id: "abbey_viewpoint",
    n: "Abbey Viewpoint",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "activity",
    l: [54.134318, -3.19746],
    i: "👁️",
  },
  {
    id: "abbey_boss",
    n: "Abbey Final Boss",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "boss",
    l: [54.134487, -3.198551],
    i: "👑",
  },
  {
    id: "abbey_hidden_stone",
    n: "Silent Stone",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "discovery",
    hidden: true,
    l: [54.138078, -3.198541],
    i: "🪨",
  },
  {
    id: "abbey_hidden_mirror",
    n: "Valley Mirror",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "discovery",
    hidden: true,
    l: [54.135888, -3.199689],
    i: "🪞",
  },
  {
    id: "abbey_hidden_forge",
    n: "Iron Forge Ruins",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "discovery",
    hidden: true,
    l: [54.134362, -3.200156],
    i: "🔥",
  },
  {
    id: "abbey_ghost_cloister",
    n: "Cloister Ghost",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "ghost",
    hidden: true,
    l: [54.135383, -3.19655],
    i: "👻",
  },
  {
    id: "abbey_headless_monk",
    n: "Headless Monk Gate",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "ghost",
    hidden: true,
    l: [0, 0],
    i: "💀",
  },
  {
    id: "abbey_whispering_trees",
    n: "Whispering Trees",
    zone: "abbey",
    set: "abbey",
    route: "abbey",
    routeStart: null,
    type: "ghost",
    hidden: true,
    l: [54.136798, -3.196861],
    i: "🌫️",
  },
];

/* =========================
     PARK PINS
  ========================= */

export const PARK_PINS = [
  {
    id: "park_start_parkave",
    n: "Park Road Gate",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: "parkroad",
    type: "start",
    l: [54.116412, -3.219966],
    i: "🚪",
  },
  {
    id: "park_start_abbeyroad",
    n: "Abbey Road Entrance",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: "abbeyroad",
    type: "start",
    l: [54.120464, -3.2203],
    i: "🚪",
  },
  {
    id: "park_start_daltonroad",
    n: "Dalton Road Entrance",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: "daltonroad",
    type: "start",
    l: [54.118661, -3.222992],
    i: "🚪",
  },
  {
    id: "park_start_greengate",
    n: "Greengate Street Entrance",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: "greengate",
    type: "start",
    l: [54.114817, -3.214354],
    i: "🚪",
  },
  {
    id: "park_start_leisure",
    n: "Leisure Centre Entrance",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: "leisure",
    type: "start",
    l: [54.11681, -3.213118],
    i: "🚪",
  },
  {
    id: "park_start_cemetery",
    n: "Cemetery Side Entrance",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: "cemetery",
    type: "start",
    l: [54.118259, -3.214589],
    i: "🚪",
  },
  {
    id: "park_bandstand",
    n: "Bandstand",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "quiz",
    theme: "festival",
    l: [54.117519, -3.21842],
    i: "🎵",
  },
  {
    id: "park_pirate_ship",
    n: "Pirate Ship Playground",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "activity",
    theme: "challenge",
    l: [54.117904, -3.216734],
    i: "🏴‍☠️",
  },
  {
    id: "park_parrot_corner",
    n: "Parrot Corner",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "quiz",
    theme: "mystery",
    l: [54.119361, -3.218797],
    i: "🦜",
  },
  {
    id: "park_mudman",
    n: "Mudman Statue",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "logic",
    theme: "mystery",
    l: [54.118436, -3.218646],
    i: "🗿",
  },
  {
    id: "park_lake",
    n: "Boating Lake",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "history",
    theme: "nature",
    l: [54.117399, -3.215484],
    i: "🦆",
  },
  {
    id: "park_bridge",
    n: "Lake Bridge",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "logic",
    theme: "nature",
    l: [54.116938, -3.214752],
    i: "🌉",
  },
  {
    id: "park_boat_hut",
    n: "Boat Hut",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "history",
    theme: "nature",
    l: [54.117955, -3.214877],
    i: "🛶",
  },
  {
    id: "park_flower_gardens",
    n: "Flower Gardens",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "quiz",
    theme: "nature",
    l: [54.117887, -3.215989],
    i: "🌺",
  },
  {
    id: "park_open_field",
    n: "Central Open Field",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "family",
    theme: "festival",
    l: [54.116753, -3.217746],
    i: "🌳",
  },
  {
    id: "park_cafe",
    n: "Park Café",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "family",
    theme: "festival",
    l: [54.11736, -3.21702],
    i: "☕",
  },
  {
    id: "park_mini_railway",
    n: "Mini Railway Station",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "history",
    theme: "history",
    l: [54.117318, -3.213263],
    i: "🚂",
  },
  {
    id: "park_leisure_centre",
    n: "Park Leisure Centre",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "quiz",
    theme: "challenge",
    l: [54.116157, -3.212451],
    i: "🏊",
  },
  {
    id: "park_skate_park",
    n: "Skate Park",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "activity",
    theme: "challenge",
    l: [54.117822, -3.21387],
    i: "🛹",
  },
  {
    id: "park_gym_park",
    n: "Outdoor Gym",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "activity",
    theme: "challenge",
    l: [54.118055, -3.214172],
    i: "💪",
  },
  {
    id: "park_bowls",
    n: "Bowling Green",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "history",
    theme: "festival",
    l: [54.117278, -3.216732],
    i: "🎳",
  },
  {
    id: "park_golf",
    n: "Golf Area",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "activity",
    theme: "festival",
    l: [54.117494, -3.217177],
    i: "⛳",
  },
  {
    id: "park_cenotaph",
    n: "Cenotaph",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "history",
    theme: "history",
    l: [54.117798, -3.220584],
    i: "🕊️",
  },
  {
    id: "park_hidden_old_tree",
    n: "Old Tree",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "discovery",
    theme: "mystery",
    hidden: true,
    l: [54.118995, -3.218479],
    i: "🌲",
  },
  {
    id: "park_hidden_quiet_bench",
    n: "Quiet Bench",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "discovery",
    theme: "mystery",
    hidden: true,
    l: [54.119403, -3.22136],
    i: "🪑",
  },
  {
    id: "park_hidden_secret_garden",
    n: "Secret Garden Spot",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "discovery",
    theme: "mystery",
    hidden: true,
    l: [54.118215, -3.21711],
    i: "🌼",
  },
  {
    id: "park_hidden_lake_spot",
    n: "Hidden Lake Spot",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "discovery",
    theme: "nature",
    hidden: true,
    l: [54.115944, -3.21441],
    i: "💧",
  },
  {
    id: "park_boss_bandstand",
    n: "Festival Revival",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "boss",
    theme: "festival",
    hidden: true,
    l: [54.117545, -3.21836],
    i: "🎺",
  },
  {
    id: "park_boss_cenotaph",
    n: "Memory Keeper",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "boss",
    theme: "history",
    hidden: true,
    l: [54.11783, -3.220545],
    i: "🏅",
  },
  {
    id: "park_boss_skate",
    n: "Park Champion",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "boss",
    theme: "challenge",
    hidden: true,
    l: [54.11786, -3.21383],
    i: "⚡",
  },
  {
    id: "park_boss_mudman",
    n: "Mudman Mystery",
    zone: "park",
    set: "park",
    route: "park",
    routeStart: null,
    type: "boss",
    theme: "mystery",
    hidden: true,
    l: [54.11848, -3.21861],
    i: "👑",
  },
];

function isValidPin(pin) {
  return (
    pin &&
    Array.isArray(pin.l) &&
    pin.l.length === 2 &&
    Number.isFinite(pin.l[0]) &&
    Number.isFinite(pin.l[1]) &&
    !(pin.l[0] === 0 && pin.l[1] === 0)
  );
}

function buildKey(pin) {
  const lat = Array.isArray(pin.l) ? pin.l[0] : 0;
  const lng = Array.isArray(pin.l) ? pin.l[1] : 0;
  return `${String(pin.n).trim().toLowerCase()}|${lat}|${lng}|${pin.set}`;
}

function dedupePins(all) {
  const seen = new Set();
  const out = [];
  for (const pin of all) {
    if (!isValidPin(pin)) continue;
    const key = buildKey(pin);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(pin);
  }
  return out;
}

export const PINS = dedupePins([
  ...BARROW_CORE_PINS,
  ...ABBEY_PINS,
  ...PARK_PINS,
]);
