/* =========================================================
   qa_groups.js
   BARROW QUEST PIN → QA GROUP MAP
   SAFE SPLIT FILE
========================================================= */

/* =========================================================
   PIN TO GROUP MAP
========================================================= */

export const PIN_GROUP_MAP = {
  home_base_marsh_st: "town_history",
  morrisons_retail: "town_history",
  salthouse_mills: "industry_history",
  cenotaph_core: "statues_memorial",
  park_bandstand_core: "park_history",
  park_railway_core: "park_history",
  boating_lake_core: "park_history",
  bridgegate_ave: "town_history",
  fryers_lane: "town_history",
  flashlight_bend: "town_history",
  red_river_walk_core: "abbey_history",
  furness_abbey_core: "abbey_history",
  dock_museum_anchor: "docks_submarines",
  town_hall_clock: "town_history",
  custom_house: "town_history",
  the_forum: "town_history",
  barrow_library: "town_history",
  henry_schneider_statue: "statues_memorial",
  james_ramsden_statue: "statues_memorial",
  old_fire_station: "town_history",
  market_hall: "town_history",
  duke_of_edinburgh: "town_history",
  emlyn_hughes_statue: "statues_memorial",
  graving_dock: "docks_submarines",
  slag_bank: "industry_history",
  walney_bridge_entrance: "islands_nature",
  earnse_bay: "islands_nature",
  walney_lighthouse: "islands_nature",
  round_house: "islands_nature",
  biggar_village: "islands_nature",
  piel_castle: "islands_nature",
  roa_island_jetty: "islands_nature",
  amphitheatre_core: "abbey_history",
  abbey_ruins_marker: "abbey_history",
  park_playground: "park_history",
  park_bowling_green_core: "park_history",
  park_cafe_core: "park_history",
  ormsgill_reservoir: "town_history",
  barrow_afc_grounds: "town_history",
  rugby_ground: "town_history",
  hollywood_park: "town_history",
  furness_general_hospital: "town_history",
  rampside_needle: "islands_nature",
  st_georges_church: "town_history",
  bae_main_gate: "docks_submarines",
  hindpool_tiger_core: "industry_history",
  dalton_road_clock: "town_history",
  voodoo_entrance: "town_history",
  bus_depot: "town_history",
  north_walney_reserve_gate: "islands_nature",
  sandy_gap_beach_access: "islands_nature",
  walney_airfield_entrance: "islands_nature",
  vickerstown_park: "islands_nature",
  king_alfred_pub: "islands_nature",
  thorny_nook: "islands_nature",
  south_walney_reserve_entrance: "islands_nature",
  walney_school: "islands_nature",
  west_shore_park: "islands_nature",
  jubilee_bridge_midpoint: "islands_nature",
  coast_road_entrance: "islands_nature",
  lifeboat_station_roa: "islands_nature",
  concle_inn: "islands_nature",
  abbey_railway_ruins: "abbey_history",
  amphitheatre_steps: "abbey_history",
  abbey_road_baptist_church: "town_history",
  nan_tait_centre: "town_history",
  barrow_fire_station: "town_history",
  submarine_memorial: "docks_submarines",
  victoria_hall: "town_history",
  barrow_golf_club: "town_history",
  hawcoat_quarry: "industry_history",
  st_pauls_church: "town_history",
  strawberry_pub: "town_history",
  red_river_waterfall: "abbey_history",
  furness_general_main_entrance: "town_history",
  roose_station_platform: "town_history",
  ship_inn_piel: "islands_nature",
  lifeboat_monument: "docks_submarines",
  newby_terrace_play_area: "town_history",
  bae_the_bridge: "docks_submarines",
  gas_terminals_main_gates: "industry_history",
  kimberly_clark_factory: "industry_history",
  spiral_ramp_town_centre: "town_history",
  barrow_park_greenhouse: "park_history",
  park_fitness_trail_start: "park_history",
  park_rockery: "park_history",
  park_rose_garden: "park_history",
  greenway_path_barrow_island: "docks_submarines",
  barrow_island_primary: "docks_submarines",
  old_brickworks: "industry_history",
  cavendish_dock_water_gate: "docks_submarines",
  bowling_alley_hollywood_park: "town_history",
  skate_park_core: "town_history",
  dock_museum_submarine: "docks_submarines",
  barrow_cricket_club: "town_history",
  twelve_laws_stone: "town_history",
  spirit_of_barrow_mural: "town_history",
  final_boss_gate_marsh_st: "town_history",
  wicks: "town_history",
  brew_room: "town_history",
  reception: "town_history",
  bitches_house: "town_history",
  dads_house: "town_history",
  tinas_house: "town_history",

  park_start_parkave: "park_history",
  park_start_abbeyroad: "park_history",
  park_start_daltonroad: "park_history",
  park_start_greengate: "park_history",
  park_start_leisure: "park_history",
  park_start_park_drive: "park_history",
  park_bandstand: "park_history",
  park_pirate_ship: "park_history",
  park_parrot_corner: "park_history",
  park_mudman: "park_history",
  park_lake: "park_history",
  park_bridge: "park_history",
  park_boat_hut: "park_history",
  park_flower_gardens: "park_history",
  park_open_field: "park_history",
  park_cafe: "park_history",
  park_mini_railway: "park_history",
  park_leisure_centre: "park_history",
  park_skate_park: "park_history",
  park_gym_park: "park_history",
  park_bowls: "park_history",
  park_golf: "park_history",
  park_cenotaph: "park_cenotaph",
  park_hidden_old_tree: "park_history",
  park_hidden_quiet_bench: "park_history",
  park_hidden_secret_garden: "park_history",
  park_hidden_lake_spot: "park_history",
  park_boss_bandstand: "park_history",
  park_boss_cenotaph: "park_cenotaph",
  park_boss_skate: "park_history",
  park_boss_mudman: "park_history",

  abbey_redriver_start: "abbey_history",
  abbey_redriver_bridge: "abbey_history",
  abbey_redriver_bend: "abbey_history",
  abbey_valley_view: "abbey_history",
  abbey_amphitheatre_entry: "abbey_history",
  abbey_hospital_entry: "abbey_history",
  abbey_hospital_field: "abbey_history",
  abbey_amphitheatre_top: "abbey_history",
  abbey_manor_gate: "abbey_history",
  abbey_outer_field: "abbey_history",
  abbey_entry_path: "abbey_history",
  abbey_woodland_entry: "abbey_history",
  abbey_monk_path: "abbey_history",
  abbey_farmland: "abbey_history",
  abbey_carpark: "abbey_history",
  abbey_ticket_gate: "abbey_history",
  abbey_cafe: "abbey_history",
  abbey_visitor_area: "abbey_history",
  abbey_gate: "abbey_history",
  abbey_church: "abbey_history",
  abbey_cloister: "abbey_history",
  abbey_chapter_house: "abbey_history",
  abbey_viewpoint: "abbey_history",
  abbey_boss: "abbey_history",
  abbey_hidden_stone: "abbey_history",
  abbey_hidden_mirror: "abbey_history",
  abbey_hidden_forge: "abbey_history",
  abbey_ghost_cloister: "abbey_ghosts",
  abbey_headless_monk: "abbey_ghosts",
  abbey_whispering_trees: "abbey_ghosts",
};

/* =========================================================
   OPTIONAL GROUP DEFINITIONS
========================================================= */

export const QA_GROUPS = {
  town_history: "town_history",
  industry_history: "industry_history",
  statues_memorial: "statues_memorial",
  park_history: "park_history",
  park_cenotaph: "park_cenotaph",
  abbey_history: "abbey_history",
  abbey_ghosts: "abbey_ghosts",
  docks_submarines: "docks_submarines",
  islands_nature: "islands_nature",
};

/* =========================================================
   HELPERS
========================================================= */

export function getGroupForPin(pinId) {
  return PIN_GROUP_MAP[pinId] || "town_history";
}

export function hasGroupForPin(pinId) {
  return Object.prototype.hasOwnProperty.call(PIN_GROUP_MAP, pinId);
}
