export const SHOP_ITEMS = [
  {
    id: "hero_duo",
    name: "Hero Duo",
    cost: 0,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Default Barrow Quest explorer.",
    ownedByDefault: true,
    defaultEquip: true,
    icon: "🧭",
    rarity: "common",
    featured: true,
  },
  {
    id: "trail_none",
    name: "No Trail",
    cost: 0,
    slot: "trail",
    type: "trail",
    section: "trails",
    desc: "No trail effect.",
    ownedByDefault: true,
    defaultEquip: true,
    icon: "➖",
    rarity: "common",
  },
  {
    id: "map_classic",
    name: "Classic Map",
    cost: 0,
    slot: "mapTheme",
    type: "mapTheme",
    section: "themes",
    desc: "Standard map theme.",
    ownedByDefault: true,
    defaultEquip: true,
    icon: "🗺️",
    rarity: "common",
  },

  {
    id: "ninja",
    name: "Ninja",
    cost: 120,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Silent and sharp.",
    icon: "🥷",
    rarity: "rare",
  },
  {
    id: "wizard",
    name: "Wizard",
    cost: 140,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Mystic explorer of old knowledge.",
    icon: "🧙",
    rarity: "rare",
  },
  {
    id: "robot",
    name: "Robot",
    cost: 160,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Metal mission machine.",
    icon: "🤖",
    rarity: "epic",
  },
  {
    id: "pirate",
    name: "Pirate",
    cost: 180,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Treasure hunter of Barrow.",
    icon: "🏴‍☠️",
    rarity: "epic",
    featured: true,
  },
  {
    id: "monk",
    name: "Monk",
    cost: 220,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Abbey spirit unlocked for the lost order.",
    icon: "⛪",
    rarity: "legendary",
  },
  {
    id: "khylan",
    name: "Khylan",
    cost: 260,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Khylan playable character skin.",
    icon: "🧒",
    rarity: "legendary",
    featured: true,
  },
  {
    id: "piper",
    name: "Piper",
    cost: 260,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Piper playable character skin.",
    icon: "👧",
    rarity: "legendary",
    featured: true,
  },
  {
    id: "char_chicken",
    name: "Chicken",
    cost: 90,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Chaotic chicken energy.",
    icon: "🐔",
    rarity: "uncommon",
    featured: true,
  },
  {
    id: "char_frog",
    name: "Frog",
    cost: 90,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Jump into missions as a frog.",
    icon: "🐸",
    rarity: "uncommon",
  },
  {
    id: "char_ghost",
    name: "Ghost",
    cost: 110,
    slot: "character",
    type: "character",
    section: "characters",
    desc: "Float through Barrow like a ghost.",
    icon: "👻",
    rarity: "rare",
  },

  {
    id: "trail_poo",
    name: "Poo Trail",
    cost: 80,
    slot: "trail",
    type: "trail",
    section: "trails",
    desc: "Leaves a poo trail behind you.",
    icon: "💩",
    rarity: "uncommon",
    featured: true,
  },
  {
    id: "trail_rainbow",
    name: "Rainbow Trail",
    cost: 120,
    slot: "trail",
    type: "trail",
    section: "trails",
    desc: "Leaves a rainbow trail behind you.",
    icon: "🌈",
    rarity: "rare",
    featured: true,
  },
  {
    id: "trail_fire",
    name: "Fire Trail",
    cost: 150,
    slot: "trail",
    type: "trail",
    section: "trails",
    desc: "A fiery trail for fast runs.",
    icon: "🔥",
    rarity: "epic",
  },
  {
    id: "trail_stars",
    name: "Star Trail",
    cost: 140,
    slot: "trail",
    type: "trail",
    section: "trails",
    desc: "Sparkling stars behind every step.",
    icon: "✨",
    rarity: "rare",
  },
  {
    id: "trail_slime",
    name: "Slime Trail",
    cost: 100,
    slot: "trail",
    type: "trail",
    section: "trails",
    desc: "A gross green slime trail.",
    icon: "🟢",
    rarity: "uncommon",
  },
  {
    id: "trail_shadow",
    name: "Shadow Trail",
    cost: 130,
    slot: "trail",
    type: "trail",
    section: "trails",
    desc: "Dark smoky shadow trail.",
    icon: "🌑",
    rarity: "rare",
  },

  {
    id: "map_dark",
    name: "Dark Map",
    cost: 100,
    slot: "mapTheme",
    type: "mapTheme",
    section: "themes",
    desc: "Dark mode map theme.",
    icon: "🌙",
    rarity: "uncommon",
  },
  {
    id: "map_neon",
    name: "Neon Map",
    cost: 140,
    slot: "mapTheme",
    type: "mapTheme",
    section: "themes",
    desc: "Bright neon style map theme.",
    icon: "💜",
    rarity: "epic",
    featured: true,
  },
  {
    id: "map_parchment",
    name: "Parchment Map",
    cost: 130,
    slot: "mapTheme",
    type: "mapTheme",
    section: "themes",
    desc: "Old parchment explorer theme.",
    icon: "📜",
    rarity: "rare",
  },

  {
    id: "route_glow_pack",
    name: "Route Glow Pack",
    cost: 180,
    slot: "effect",
    type: "utility",
    section: "boosts",
    desc: "Adds glow styling to captured route markers.",
    icon: "🔆",
    rarity: "epic",
  },
  {
    id: "hint_basic",
    name: "Hint Token",
    cost: 50,
    slot: "consumable",
    type: "consumable",
    section: "boosts",
    desc: "Basic extra hint for tricky missions.",
    stackable: true,
    icon: "💡",
    rarity: "common",
  },
  {
    id: "hint_plus",
    name: "Mega Hint",
    cost: 90,
    slot: "consumable",
    type: "consumable",
    section: "boosts",
    desc: "A stronger mission hint.",
    stackable: true,
    icon: "🚨",
    rarity: "rare",
  },
  {
    id: "xp_boost_small",
    name: "XP Boost",
    cost: 110,
    slot: "consumable",
    type: "consumable",
    section: "boosts",
    desc: "Small XP boost item.",
    stackable: true,
    icon: "⭐",
    rarity: "rare",
  },
  {
    id: "coin_boost_small",
    name: "Coin Boost",
    cost: 110,
    slot: "consumable",
    type: "consumable",
    section: "boosts",
    desc: "Small coin boost item.",
    stackable: true,
    icon: "🪙",
    rarity: "rare",
  },
];
